package Quiz_Packages.Play;

import java.awt.event.ActionListener;
import java.util.HashSet;
import java.util.Set;




public class GUI_QuizSpielen extends javax.swing.JFrame {

    public static final String BUTTONA = "BUTTONA";
    public static final String BUTTONB = "BUTTONB";
    public static final String BUTTONC = "BUTTONC";
    public static final String BUTTOND = "BUTTOND";
    public static final String BUTTONWAIT = "BUTTONWAIT";
    public static final String FINISHED_QUIZ = "FINISHED_QUIZ";

    
    
    public GUI_QuizSpielen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFrage = new javax.swing.JLabel();
        buttonB = new javax.swing.JButton();
        buttonD = new javax.swing.JButton();
        buttonA = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        buttonWait = new javax.swing.JButton();
        finished = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(604, 494));
        setResizable(false);

        labelFrage.setText("jLabel1");
        buttonA.setText("A");
        buttonA.setActionCommand(Quiz_Packages.Play.GUI_QuizSpielen.BUTTONA);

        buttonB.setText("B");
        buttonB.setActionCommand(Quiz_Packages.Play.GUI_QuizSpielen.BUTTONB);

        buttonC.setText("C");
        buttonC.setActionCommand(Quiz_Packages.Play.GUI_QuizSpielen.BUTTONC);

        buttonD.setText("D");
        buttonD.setActionCommand(Quiz_Packages.Play.GUI_QuizSpielen.BUTTOND);

        buttonWait.setActionCommand(Quiz_Packages.Play.GUI_QuizSpielen.BUTTONWAIT);
        buttonWait.setVisible(false);
        buttonWait.setText("Sie können diese Frage überspringen");

        finished.setText("Statistik anzeigen");
        finished.setActionCommand(FINISHED_QUIZ);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelFrage)
                        .addComponent(buttonWait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonA, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonB, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonD, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(finished, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelFrage)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonB, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonA, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonD, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(buttonWait, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(finished, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonA;
    private javax.swing.JButton buttonB;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonD;
    private javax.swing.JButton buttonWait;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton finished;
    private javax.swing.JLabel labelFrage;
    // End of variables declaration//GEN-END:variables





 public void SetButtonsAText(String s){buttonA.setText(s);}                 
    public void SetButtonsBText(String s){buttonB.setText(s);}
    public void SetButtonsCText(String s){buttonC.setText(s);}
    public void SetButtonsDText(String s){buttonD.setText(s);}
    public void SetLableText(String s){labelFrage.setText(s);}
    public void SetButtonWaitText(String s){buttonWait.setText(s);}
    public void enableButtonWait(){
        buttonWait.setVisible(true);
        buttonWait.setEnabled(true);    
    }
    public void disableButtonWait(){
        //buttonWait.setVisible(false);
        buttonWait.setEnabled(false);
    }
    public void disableButtons(){
        buttonA.setVisible(false);
        buttonB.setVisible(false);
        buttonC.setVisible(false);
        buttonD.setVisible(false);
        buttonWait.setVisible(false);
        
    }
    public void setFinishedVisible(){finished.setVisible(true);}
    public String getButtonsAText(){return buttonA.getText();}
    public String getButtonsBText(){return buttonB.getText();}
    public String getButtonsCText(){return buttonC.getText();}
    public String getButtonsDText(){return buttonD.getText();}
    public void addListener(ActionListener actions){
        buttonA.addActionListener(actions);
        buttonB.addActionListener(actions);
        buttonC.addActionListener(actions);
        buttonD.addActionListener(actions);
        buttonWait.addActionListener(actions);
        finished.addActionListener(actions);
    }




}
